version: '3'

networks:
  microservices:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./transcription-gateway:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - microservices

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./transcription-gateway:/var/www
    ports:
      - "9000:9000"
    networks:
      - microservices

  transcriber:
    build:
      context: .
      dockerfile: Dockerfile-transcriber
    container_name: transcriber
    volumes:
      - ./transcriber:/var/www
